spring:
  datasource:
    url: jdbc:mysql://localhost:3306/graduate?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: "root"
    password: "root"
  jdbc:
    template:
      query-timeout: 3
  thymeleaf:
    encoding: UTF-8
    enabled: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml